#!/usr/bin/python3
from flask import Flask
from flask_restful import Api, Resource, reqparse

import board
import neopixel

pixels = neopixel.NeoPixel(board.D18, 150, brightness=0.2, auto_write=False, pixel_order=neopixel.RGB)

def enable_led(led):
    # Turn on all the leds for the tile.
    for index in range(led["start", led["end"]]):
        pixels[index] = (led["r"], led["g"], led["b"])
    
    # Send the new color.
    pixels.show()

def disable_led(name):
    # Turn off all the leds for the tile.
    for index in range(led["start", led["end"]]):
        pixels[index] = (0, 0, 0)
    
    # Send the new color.
    pixels.show()

class Led(Resource):
    def get(self, name):
        for led in leds:
            if led["name"] == name:
                return led, 200
        return "led not found", 404

    def post(self, name):
        for led in leds:
            if led["name"] == name:
                enable_led(led)

                # Return new status.
                led["enabled"] = True
                return led, 200
        return "led not found", 404

    def delete(self, name):
        for led in leds:
            if led["name"] == name:
                disable_led(led)

                # Return new status.
                led["enabled"] = False
                return led, 200
        return "led not found", 404

app = Flask(__name__)
api = Api(app)
api.add_resource(Led, "/led/<string:name>")
app.run(debug=True)